"""Add is_active to students

Revision ID: ca44164d4b9d
Revises: 1b47899ca658
Create Date: 2026-07-05 12:16:53.081141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca44164d4b9d'
down_revision = '1b47899ca658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    op.execute("UPDATE students SET is_active = TRUE WHERE is_active IS NULL")

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('is_active', existing_type=sa.Boolean(), nullable=False, server_default=sa.true())

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
