# Generated by Django 5.2.15 on 2026-07-06 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('library', '0002_book_publication_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adapted_movies', to='library.book'),
        ),
    ]
